apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test2-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/faizulkhan56/gitops-infra.git
    targetRevision: HEAD
    path: apps/test2/test
  destination:
    server: https://kubernetes.default.svc
    namespace: test2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
